import { sendJob } from "@/lib/queue/jobs";

/**
 * Queues a magic link email to the pgBoss worker.
 *
 * Instead of sending the email synchronously (which would block the
 * request handler on slow SMTP calls), we enqueue a `send-email` job.
 * The pgBoss worker process picks it up and sends the email via
 * Nodemailer using SMTP credentials from env vars.
 *
 * In development (without SMTP configured), the worker will log a
 * warning. The magic link URL is also logged here for convenience.
 *
 * @param email  — recipient email address
 * @param url    — the magic link URL generated by BetterAuth
 */
export async function sendMagicLinkEmail(
  email: string,
  url: string,
): Promise<void> {
  // For local development — log the link so you can click it
  console.log(`[magic-link] Magic link for ${email}: ${url}`);

  // Queue the actual email to be sent by the worker
  const appName = process.env.NEXT_PUBLIC_APP_URL
    ? new URL(process.env.NEXT_PUBLIC_APP_URL).host
    : "Next.js Starter";

  const html = `
    <html>
      <body style="font-family: system-ui, sans-serif; line-height: 1.6;">
        <h2 style="color: #3b82f6;">Sign in to ${appName}</h2>
        <p>Click the button below to sign in (link expires in 30 minutes):</p>
        <a
          href="${url}"
          style="display: inline-block; padding: 12px 24px; background: #3b82f6; color: white; text-decoration: none; border-radius: 6px; margin: 16px 0;"
        >
          Sign in
        </a>
        <p style="font-size: 12px; color: #6b7280;">Or copy and paste this URL: ${url}</p>
      </body>
    </html>
  `;

  const text = `Sign in to ${appName}\n\nClick the link below to sign in:\n${url}\n\nThis link expires in 30 minutes.`;

  await sendJob("send-email", {
    to: email,
    subject: `Sign in to ${appName}`,
    html,
    text,
  });
}
