import { sendJob } from "@/lib/queue/jobs";
import { APP_URL, MAGIC_LINK_EXPIRY_SECONDS } from "@/lib/auth/config";
import { renderMagicLinkEmail } from "@/lib/email/templates/magic-link";

// Derived from the same constant the plugin is configured with, so the copy
// can never claim an expiry the token does not actually have.
const MAGIC_LINK_EXPIRY_MINUTES = Math.round(MAGIC_LINK_EXPIRY_SECONDS / 60);

/**
 * Queues a magic link email for the pgBoss worker.
 *
 * The email is enqueued rather than sent inline so a slow or unreachable SMTP
 * server can never block (or fail) the sign-in request. The worker delivers it.
 *
 * @param email  recipient address
 * @param url    the magic link URL generated by BetterAuth
 */
export async function sendMagicLinkEmail(
  email: string,
  url: string,
): Promise<void> {
  if (process.env.NODE_ENV === "development") {
    // Saves a trip to the mail catcher while developing.
    console.log(`[magic-link] ${email} -> ${url}`);
  }

  const appName = deriveAppName();
  const { subject, html, text } = renderMagicLinkEmail({
    appName,
    url,
    expiresInMinutes: MAGIC_LINK_EXPIRY_MINUTES,
  });

  await sendJob("send-email", { to: email, subject, html, text });
}

/**
 * A human-readable product name for the email.
 *
 * Falls back through an explicit override, then the app's hostname, then a
 * generic label — a bare "localhost:3003" in a subject line looks broken.
 */
function deriveAppName(): string {
  if (process.env.NEXT_PUBLIC_APP_NAME) return process.env.NEXT_PUBLIC_APP_NAME;

  try {
    const { hostname } = new URL(APP_URL);
    if (hostname === "localhost" || hostname === "127.0.0.1") {
      return "Next.js Starter";
    }
    return hostname.replace(/^www\./, "");
  } catch {
    return "Next.js Starter";
  }
}
